### PR TITLE
3.11.0

### PR DESCRIPTION
**Pull request by calvinmetcalf**
have to merge it this way due to protected branch hook branch hook

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
tag is already pushed, not going to publish until this is merged in

**Comment by calvinmetcalf** [comment]
and we are green

**Comment by calvinmetcalf** [comment]
and published to npm

**Comment by dcousens** [comment]
@calvinmetcalf cheers,  and annoying as it can be,  the protected branch hook is great for keeping up the visibility. 
Thanks :+1:

**Pull request merged**
