### PR TITLE
jspm node support

### PR DESCRIPTION
**Pull request by guybedford**
This PR includes the necessary jspm configuration for this package to work in Node with the coming jspm 0.17 release, allowing this single package to provide both client and server support.

I completely understand if you'd rather not support this here, but it will simplify user configuration locally having it in one place. There is no maintenance burden either as I would continue to maintain this personally.

Just let me know if you have any questions at all, and thanks for considering.

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
I'm generally supportive of this as it seems like a pretty minor thing to do with no obvious downside, of course that's what [I thought about jam support](https://github.com/webpack/webpack/issues/1118).

**Comment by guybedford** [comment]
Thanks! Yes second-order checking does get somewhat complicated when tools try to second-guess eachother. As mentioned, I'll sort out any (possible) discussions around this override in future though if you just ping me in.

**Comment by jprichardson** [comment]
I'm -1 on this. Not to say that my mind couldn't be changed.

Things that we need to figure out first:

1. Why `jspm` in the first place? I've read a few things about it, but the value proposition is not clear to me. A cursory glance at the web site suggests a few minor improvements over `npm`. The ones that stick out are AMD/ES6 module support. AMD support isn't a big deal as other tooling can take care of that. ES6 module support is already handled well with Babel. Some bundler tools like Rollup are doing a nice job of leveraging the benefits of ES6 modules, but I don't see that with jspm. Github dependencies, npm can already do that (albeit a bit flakey), but it still can.

2. This is a question more for our @crypto-browserify/owners team... if we accept this, where do we draw the line? Do we need to add bower support to then? What about all of the other package managers?

**Comment by calvinmetcalf** [comment]
1. because @guybedford asked nicely and he's the one who who created it
2. I 100% agree that we should draw some lines and I'd say adding a static property to the package.json would be pretty feasible to do, if somebody wanted us to add a second config file that we had to update in tandem with the main one, or a a property that we had to update each time we updating things that would probably be too much work unless there were some really tangible benefits (this would rule out bower btw).

**Comment by jprichardson** [comment]
@calvinmetcalf thanks :)

1. To be clear with my questioning here, I hope that my tone didn't come off as unnecessary hostile / aggressive. I was trying to be sincere :)

2. This seems reasonable.

**Comment by ForbesLindesay** [comment]
I think the "where do we draw the line" issue is hugely important.  What makes this package manager and this module special?  There are over 20 crypto-browserify modules.  Should we update all of them for jspm?  Should we be testing to make sure they keep working in jspm?  I personally am listed as an owner of over 400 packages, should I update all of them to work with jspm?

What information does jspm need that it couldn't fetch correctly by default from package.json.  I don't have a problem with cases where a module needs special handling, but it seems to me that this module will do the right thing out of the box, providing your package manager supports the `"browser"` field.

**Comment by calvinmetcalf** [comment]
@ForbesLindesay so the we can probably avoid having to answer all of those questions right now becuase @guybedford is making a pretty clear ask  about what he wants.

As for your second question that I'll leave that to @guybedford to explain in detail but it looks like the data being added is similar to the browser field but jspm specific as it has a jspm style namespace

**Comment by guybedford** [comment]
Thanks for the considered discussion here. As mentioned, I take full maintenance responsibility here, but don't expect any further updates will ever be needed unless this package goes through breaking changes in future. I have also waited to send any PR for configs until now since the jspm configuration system has finally stabilized with the upcoming 0.17 release.

@ForbesLindesay in terms of drawing the line - all of the other crypto npm packages work out of the box in jspm 0.17 respecting the browser config etc. The exception here is just that this is one of 22 browserify packages which need to conditionally be replaced with Node core modules in the Node environment when running in jspm to allow JS to run properly between both client and server, and that information is currently not available to jspm (while Node implements it in its resolution system).

**Comment by dominictarr** [comment]
Also... looking at your format, it looks like it's remapping this module in node? but this should only apply in the browser and will use core crypto library in node.

right, @guybedford  so browserify handles the mapping instead of node, and basically has a small set of polyfils that it uses when you request a core module, and those are hardcoded internally. what are the advantages of why and how you have done it? (would this just be better as a standard?)

I imagine you have made other similar pull requests and other people are having discussions such as this.
I don't think that you (or anyone) persionally maintaining this is a solution (there are now over 100k npm modules) it would be far better if it was to _just work_.

**Comment by dcousens** [comment]
weak NACK.
I'm not sure why its justified.

**Comment by guybedford** [comment]
To explain the configuration it just says that when loading this package in a NodeJS environment, instead of loading the main entry point here, load the Node core version of crypto. This allows `jspm install crypto=npm:crypto-browserify` to provide an `import crypto from 'crypto'` which will work and build in all environments.

There are 22 of these PRs just for the core Browserify libs, to give jspm full universal JS support. All other configurations do just work in jspm detected from the npm conventions but this is specifically the Node core branching case.

The alternative is to have a wrapper package, but I don't want to introduce an unnecessary dependency, so the effective best alternative does just end up being my running a fork, and hence this PR.

**Comment by ForbesLindesay** [comment]
Two points:

1. All the modules that crypto-browserify require already just defer to the built in `crypto` module in node.js.  This means that there really is no meaningful performance hit to using this module directly in node instead of the built in crypto.
2. An infinitely better method than forking the ecosystem would be to just automatically provide the builtins like browserify does.  Why make people do `jspm install crypto=npm:crypto-browserify` for packages that work out of the box in most other js environments.  This pushes a maintenance burden from the package manager (where it can be maintained in one single place by someone who likely cares and uses the product) onto individual package maintainers (where each one has to maintain it separately, and most probably don't use your package manager).

A quick look at jspm returns the tag line "Registry and format agnostic JavaScript package manager".  There's no such thing as a "format agnostic" package manager; you're just requiring packages to use metadata in your own preferred format, rather than the standardised formats used by node & browserify.  You're also no more "registry agnostic" than npm, which already supports not only the npm registry and github, but also arbitrary tarball urls, git urls and file system paths.

**Comment by guybedford** [comment]
@ForbesLindesay sure let me do my best to answer these questions succinctly. It's great to go though these things, but we should also be careful not to sideline the underlying PR discussion here. If you want to discuss underlying jspm questions in further detail, please feel free to post a question to https://github.com/jspm/jspm-cli/issues anytime and I'm more than happy to have discussions there.

> 1. All the modules that crypto-browserify require already just defer to the built in crypto module in node.js. This means that there really is no meaningful performance hit to using this module directly in node instead of the built in crypto.

Yes, that is fine in Node, but we are not building the assumption into jspm that `require('crypto')` must always resolve to Node core crypto. Instead this package is treated as the main crypto entry point, which can then defer to the Node core crypto itself with this config (which is available at `require('@node/crypto')`).

> 2. An infinitely better method than forking the ecosystem would be to just automatically provide the builtins like browserify does. Why make people do jspm install crypto=npm:crypto-browserify for packages that work out of the box in most other js environments. This pushes a maintenance burden from the package manager (where it can be maintained in one single place by someone who likely cares and uses the product) onto individual package maintainers (where each one has to maintain it separately, and most probably don't use your package manager).

We certainly do not make anyone type `jspm install crypto=npm:crypto-browserify`. The two ways users will get this is if installing an npm module that uses Node core crypto it will automatically add this package as a dependency, otherwise if users want crypto they would install it as - `jspm install crypto`, which is effectively a shorthand for the above. This way the browserify libs are installed as needed into projects like any other dependency, instead of being cached as part of jspm itself. This work is exactly about providing the Browserify builtins automatically in jspm.

The format agnostic in jspm refers to module format, it could definitely be worth clarifying that though.

**Comment by ForbesLindesay** [comment]
What I'm not understanding, is why this logic should live in these packages, rather than as part of jspm.  I feel that it should be the responsibility of jspm to figure out that `require('crypto')` in a node environment should point to the core node module and that in a browser environment it should point to crypto-browserify.  Given that `crypto` is a core module, it doesn't make sense to mutate it to support lots of different package managers, rather the package managers should figure out how to handle core modules for themselves.

**Comment by guybedford** [comment]
That's a good question - so jspm does detect that `require('crypto')` represents the Node core module, and sets it up as an alias of the `npm:crypto-browserify` package. The specific restriction here is that we only have the ability to provide conditional branching of code at the package level in SystemJS. That is, I need one package to represent `crypto` in jspm, which can then provide the necessary branching config within itself (as in this PR) to work in all environments. Having all configurations scoped to packages, with simple package aliasing on top of that forms the conceptual model for configuration in SystemJS and jspm. Global-level branching would require a global branching configuration outside of the package level, but these sorts of global configs are less preferable to package-scoped configuration as one loses the benefits of encapsulation. Just let me know if I'm no longer making sense though.

**Comment by guybedford** [comment]
Is there any chance we might still get consensus for a merge here? I can run a fork no problem if you want to close this too.

**Comment by guybedford** [comment]
I can work around this no problem.

**Pull request closed without merging**
