### PR TITLE
browserify-sign 4.0.1 breaks public interface.

### PR DESCRIPTION
**Pull request by rharriso**

### CODE REVIEW

**Comment by rmg** [comment]
Related to #161 and crypto-browserify/browserify-sign#34

**Comment by rmg** [comment]
Looks like this is fixed in v4.0.2 which was released by @calvinmetcalf a couple minutes after this PR was opened. Hopefully quick enough that most users won't even have noticed :-D

**Comment by rharriso** [comment]
@rmg nice!

**Comment by calvinmetcalf** [comment]
ok now it's fixed in 4.0.3, forgot we had a files array in that package

**Comment by rharriso** [comment]
@calvinmetcalf lol, thankfully we have integration tests!

**Pull request closed without merging**
