### PR TITLE
pull out diffie-hellman

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by dcousens** [comment]
Will review. ETA 24 - 48 hrs.

**Comment by dcousens** [comment]
Will finish https://github.com/crypto-browserify/diffie-hellman/pull/11 then I'll be good to ACK.

**Comment by calvinmetcalf** [comment]
rebased

**Comment by ForbesLindesay** [comment]
This looks like it's good to go now.

**Comment by calvinmetcalf** [comment]
1efee1790e4f66894c3476c4b00d2300dc4eadf6 3.9.11

**Pull request closed without merging**
