### PR TITLE
add dependencies tree to README.md

### PR DESCRIPTION
**Pull request by fanatid**
One of disadvantages of the small modules that you need walk between repositories and looking *who depend from who?*
I tired do this and wrote script that create tree that shows dependencies, I'm sure that this will helpful for every one who want review code.
Also script generate tables with 3 bages: npm version, dependencies status through david-dm.org and count of issues on github.

[rendered README.md in my repository](https://github.com/fanatid/crypto-browserify/tree/a31e137c0b44a45507285931d6841f0524a924fc#dependencies-tree)

### CODE REVIEW

**Comment by dominictarr** [comment]
this is pretty good! :+1: especially for security critical projects!

**Comment by fanatid** [comment]
Right now script gets information from installed packages. But should make requests to npmjs.com, you agree?

**Comment by dominictarr** [comment]
I don't think it makes that much difference. maybe best is use `npm shrinkwrap` to output entire dependency tree, and use that.

**Comment by fanatid** [comment]
dependencies tree generator moved to own repository [fanatid/npm-rdtree-markdown](https://github.com/fanatid/npm-rdtree-markdown)

**Comment by calvinmetcalf** [comment]
you should also totally publish it on npm otherwise this looks good

**Comment by fanatid** [comment]
@calvinmetcalf publish `npm-rdtree-markdown`?

**Comment by calvinmetcalf** [comment]
yes I can see this being generally useful to other projects

**Comment by calvinmetcalf** [comment]
maybe just call it rdtree

**Comment by fanatid** [comment]
I wanted create generator as web tool, but `registry.npmjs.org` doesn't support *CORS*.
I think that I'll publish after this PR will be merged :)

**Comment by calvinmetcalf** [comment]
true, but  
`https://kublai.cloudant.com/skimdb` does support cors

**Comment by calvinmetcalf** [comment]
tests need to pass to merge, and you need to be in the repo to run the tests so running them as #151

**Comment by jprichardson** [comment]
> you should also totally publish it on npm otherwise this looks good

Nice work @fanatid!

**Comment by dcousens** [comment]
Can this be inserted as a pre-publish step?

**Comment by fanatid** [comment]
@dcousens good idea, I think I can do this with sed/awk/etc

**Comment by fanatid** [comment]
updated (added script `prepublish`)

**Comment by fanatid** [comment]
ping

**Comment by calvinmetcalf** [comment]
rebased and restarting the tests

**Comment by fanatid** [comment]
ie fails on windows 10, can somebody restart this test suite?

**Comment by calvinmetcalf** [comment]
it would seem that IE 11 on saucelabs has stopped working, not the test itself the runner on saucelabs we may want to bypass the required check for this pull ...

**Comment by fanatid** [comment]
@calvinmetcalf can you try restart tests? Hope that in this time tests will not fail...

**Comment by fanatid** [comment]
As I see, this PR is not very interesting for @crypto-browserify team, I'll close it.
Probably I should write service for generating this tree, on heroku or something.
Please also close related PR #151

**Pull request closed without merging**
