### PR TITLE
Modularize pbkdf2-compat

### PR DESCRIPTION
**Pull request by ForbesLindesay**

### CODE REVIEW

**Comment by dcousens** [comment]
ACK

**Comment by jprichardson** [comment]
ACK

**Comment by calvinmetcalf** [comment]
3.9.12  61056c06a520494d2c1781d6f9eb089bc1e38dc9 also sending @ForbesLindesay an invite to the org he's hooked

**Comment by ForbesLindesay** [comment]
@calvinmetcalf Thanks.  Is there any process written down for how pull requests are reviewed?  I'm guessing from what I've seen that tit takes two "ACK"s and then the third person merges?

**Comment by calvinmetcalf** [comment]
I usually wait for an ack, unless its a repo that one person has some ownership on (like @dcousens for this one) then I wait for that person.

**Pull request closed without merging**
