### PR TITLE
more explicit exports

### PR DESCRIPTION
**Pull request by calvinmetcalf**
for @indutny

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
see #168

**Comment by indutny** [comment]
❤️ 

Thank you!

**Comment by indutny** [comment]
This shaves few more kilobytes after tree shaking. Ideally it would great if my lib could shake off most of unused stuff.

**Comment by indutny** [comment]
...right now it is blocked by lack of information internally, but this PR removes at least one major roadblock.

**Comment by dcousens** [comment]
nit: the exports could be sorted lexicographically,  comparison would be easier

**Comment by calvinmetcalf** [comment]
@dcousens I kept the previous sorting I believe

**Comment by coltongit** [comment]
Did this fix #168? Or can there be more done on that issue than just this PR?

**Pull request merged**
