### PR TITLE
make prng/pseudorandombytes an alias for rng/randombytes

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by dcousens** [comment]
I'm OK with this,  we can perhaps improve it over time.

**Comment by calvinmetcalf** [comment]
as of iojs/io.js#557 this is also the case in node

**Comment by dcousens** [comment]
ACK

**Comment by jprichardson** [comment]
ACK

**Comment by calvinmetcalf** [comment]
3.9.10

**Pull request merged**
