### PR TITLE
update sha.js to 2.3.5 - optimization for sha256/512

### PR DESCRIPTION
**Pull request by dominictarr**
after merging @dcousens's improvements to sha.js https://github.com/dominictarr/sha.js/pull/19#issuecomment-69729879

### CODE REVIEW

**Comment by dcousens** [comment]
ACK, but I'm biased, haha.

**Comment by calvinmetcalf** [comment]
Looks good, I'd be curious about your benchmarking setup

**Comment by dominictarr** [comment]
It's the benchmarking that I used for this: http://dominictarr.github.io/crypto-bench/

**Comment by dominictarr** [comment]
okay merging.

**Comment by dominictarr** [comment]
merged into 3.9.6, along with updating metadata to point to crypto-browserify org!

**Pull request merged**
