### PR TITLE
pull out hashes and hmacs

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by jprichardson** [comment]
ACK

**Comment by calvinmetcalf** [comment]
would this be patch or minor do you think ?

**Comment by calvinmetcalf** [comment]
The broken out modules use node apis in node so the tests no longer test the JavaScript, in other words we need browser tests, provo will likely be easiest

**Comment by dominictarr** [comment]
if the module falls back to node, is needs to be a way to force the browser version (in node) so that it is convienient to benchmark.

**Comment by calvinmetcalf** [comment]
you can do (currently) require('create-hash/create-hash') and require('create-hmac/create-hmac') maybe standardize on the file being called browser so you can do require('lib/browser')

**Comment by dcousens** [comment]
How does it fall back to node APIs?

**Comment by dcousens** [comment]
Before this is merged, I'd like to cross verify against the other repositories to see what changes have been made in the extraction.

**Comment by calvinmetcalf** [comment]
this doesn't include randomBytes

**Comment by calvinmetcalf** [comment]
it uses the [browser field](https://github.com/crypto-browserify/createHash/blob/master/package.json#L5) of the packages to toggle between [index.js](https://github.com/crypto-browserify/createHash/blob/master/package.json#L5) on node and [another file](https://github.com/crypto-browserify/createHash/blob/master/create-hash.js) in the browser. A better description would be that it uses the native api in node.

**Comment by calvinmetcalf** [comment]
ok I'm updating createHmac and createHash to be easier to test will ping again when this is ready

**Comment by calvinmetcalf** [comment]
ok updated, this now tests against both the version this library uses (aka from the tests `require('../').createHash/createHmac`) to make sure it's included correctly and the JavaScript port being imported (aka `require('create-hash/browser')` and `require('create-hmac/browser')`.

This only externalizes hmacs and hashes, aka does not include any changes to the random numbers.

**Comment by dcousens** [comment]
ACK.

**Comment by calvinmetcalf** [comment]
3.9.7

**Pull request merged**
