### PR TITLE
Browser tests

### PR DESCRIPTION
**Pull request by calvinmetcalf**
at it again, inspired by crypto-browserify/createHash#8

### CODE REVIEW

**Comment by dcousens** [comment]
:+1:

**Comment by dcousens** [comment]
The browser tests still aren't passing on travis?

**Comment by calvinmetcalf** [comment]
Yeah not yet

**Comment by calvinmetcalf** [comment]
we apparently do not support opera because it fails to be able to generate random numbers, I believe they didn't support that api because the result of Math.random() was actually cryptographically secure there, not a big deal because it's just the earlier pre blink based operae.

**Comment by calvinmetcalf** [comment]
hm also ie9 fails due to the poor RNG, we may need to shim a non cryptographically secure one for the tests

**Comment by calvinmetcalf** [comment]
ok all pasing now except android (due to known bug) and safari due to...it being the new IE?

**Comment by dcousens** [comment]
Can't be merged unless tests are passing :S

**Comment by calvinmetcalf** [comment]
Oh I know

**Comment by calvinmetcalf** [comment]
getting weird flakiness on ipads...it's never the same version that fails

**Comment by calvinmetcalf** [comment]
that being said it's pretty consistently md5 tests that are failing

**Comment by calvinmetcalf** [comment]
its consistently the md5 test that the ipad (not iphone) is failing, so this could be real...

**Comment by calvinmetcalf** [comment]
I've been trying all day to reproduce on an ipad simulator (like in saucelabs) and can't making me suspect its a saucelabs issue

**Comment by calvinmetcalf** [comment]
Ping @dcousens on this I think we can merge without iPad s

**Comment by dcousens** [comment]
ACK on merge, but, if you could outline where you got up with the iPad testing, that would be useful for future.

**Comment by calvinmetcalf** [comment]
basically I set up the emulator with xcode on my mac and tested against all the failing version several times and was unable to reproduce the issue.

**Comment by dcousens** [comment]
:+1: cheers

**Pull request merged**
